### ISSUE TITLE
Encrypt passwords and validates encrypted passwords on the server

### ISSUE THREAD

**Issue by mctolentino** [chingu-voyages/v8-bears-team-22#13]

**Comment by mctolentino** [comment]
References:
https://medium.com/front-end-weekly/learn-using-jwt-with-passport-authentication-9761539c4314
https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6
https://medium.freecodecamp.org/learn-how-to-handle-authentication-with-node-using-passport-js-4a56ed18e81e
https://hackernoon.com/javascript-promises-and-why-async-await-wins-the-battle-4fc9d15d509f
https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016
https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons

**Comment by mctolentino** [comment]
I didn't use passportjs and mongoose for now, 
passportjs - maybe we could reconsider using this when we add more login strategies (fb/google/twitter etc). Since we're only using username and password for now, I think it adds a bit of complexity without adding too much value.
mongoose - requires for us to understand it's schema api, not sure if it's worth it. maybe we could add it when db structure gets a bit more complex.

**Comment by mctolentino** [comment]
Done with hashing passwords and saving the salt and hash with the user data. Need to create signing of jwt token and sending it back to react client, then in the client, saving it into local storage and using it to subsequent requests.

**Comment by mctolentino** [comment]
References for JWT:
https://medium.com/dev-bits/a-guide-for-adding-jwt-token-based-authentication-to-your-single-page-nodejs-applications-c403f7cf04f4
https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6
https://medium.com/@patrykcieszkowski/jwt-authentication-in-express-js-ee898b87a60

**Comment by denibulkashvili** [comment]
@maki Could you push the code you have so far? I would like to have a look
