### ISSUE TITLE
Make header and sidebar

### ISSUE THREAD

**Issue by mctolentino** [chingu-voyages/v8-bears-team-22#6]

**Comment by mctolentino** [comment]
Create a sidebar based on the mockup:
![app-account](https://user-images.githubusercontent.com/1000088/55081254-7787ec80-50da-11e9-8774-28bfdd633283.png)

**Comment by mctolentino** [comment]
Material-UI's progress bar doesn't have the ability to add a percentage text inside the progress circle. I'll just make a custom component for it based on https://codepen.io/bbrady/pen/ozrjKE.

**Comment by denibulkashvili** [comment]
@mctolentino that looks really good, great find
